CREATE TABLE ESHOP.ORDERS
(
    ID BIGINT PRIMARY KEY NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_ITEM_ID BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    TOTAL_COST DOUBLE NOT NULL,
    ORDER_STATUS VARCHAR(30) NOT NULL
);